using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace ItemPropertyFormulaPatcher;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args) => SynthesisPipeline.Instance
        .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
        .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
        .SetTypicalOpen(GameRelease.SkyrimSE, "ItemPropertyFormulaPatch.esp")
        .Run(args);

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) =>
        PatchRunner.Run(state.LoadOrder.PriorityOrder.Where(x => x.Mod is not null).Select(x => x.Mod!),
            state.PatchMod, _settings.Value);
}
